
package interfaccia;

import controller.GestioneSalvataggi;
import entita.Giocatore;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Classe che rappresenta l'interfaccia di avvio del gioco.
 */
public class InterfacciaAvvioGioco extends javax.swing.JFrame {

    private final Giocatore giocatore = new Giocatore("Utente");
    
    /**
     * Costruttore di default.
     */
    public InterfacciaAvvioGioco() {
        this.initComponents();
        this.inizializzaIcone();
        this.centraFrame();
    }
    
    /**
     * Metodo che centra il frame.
     */
    private void centraFrame() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    }
    
    /**
     * Metodo che inizializza le icone.
     */
    private void inizializzaIcone() {
        this.labelCopertina.setIcon(new ImageIcon("./risorse/img/Copertina.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCopertina = new javax.swing.JLabel();
        buttonNuovaPartita = new javax.swing.JButton();
        buttonContinua = new javax.swing.JButton();
        buttonEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AtomicQuest");
        setFocusableWindowState(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        buttonNuovaPartita.setBackground(new java.awt.Color(183, 255, 50));
        buttonNuovaPartita.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        buttonNuovaPartita.setForeground(new java.awt.Color(0, 0, 0));
        buttonNuovaPartita.setText("NUOVA PARTITA");
        buttonNuovaPartita.setBorder(null);
        buttonNuovaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuovaPartitaActionPerformed(evt);
            }
        });

        buttonContinua.setBackground(new java.awt.Color(247, 195, 43));
        buttonContinua.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        buttonContinua.setForeground(new java.awt.Color(0, 0, 0));
        buttonContinua.setText("CONTINUA");
        buttonContinua.setBorder(null);
        buttonContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinuaActionPerformed(evt);
            }
        });

        buttonEsci.setBackground(new java.awt.Color(0, 0, 0));
        buttonEsci.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        buttonEsci.setForeground(new java.awt.Color(204, 255, 51));
        buttonEsci.setText("ESCI");
        buttonEsci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51), 2));
        buttonEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNuovaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(buttonContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(buttonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(labelCopertina, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelCopertina, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuovaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuovaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuovaPartitaActionPerformed
        new InterfacciaGioco(this.giocatore).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonNuovaPartitaActionPerformed

    private void buttonEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsciActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonEsciActionPerformed

    private void buttonContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinuaActionPerformed
        if (GestioneSalvataggi.isDBVuoto()) {
            JOptionPane.showMessageDialog(this, "Non hai salvato nessuna partita");
        } else {
            new InterfacciaGioco().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonContinuaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContinua;
    private javax.swing.JButton buttonEsci;
    private javax.swing.JButton buttonNuovaPartita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCopertina;
    // End of variables declaration//GEN-END:variables
}
