
package interfaccia;

import entita.Giocatore;
import entita.Items;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


public class InterfacciaInventario extends javax.swing.JFrame {
    
    public InterfacciaInventario(Giocatore giocatore) {
        initComponents();
        this.centraFrame();
        this.visualizzaInventario(giocatore);
    }
    
    private void visualizzaInventario(Giocatore giocatore) {
        if (giocatore.getInventario().contieneItem(Items.TESSERINO)) {
            this.labelTesserino.setIcon(new ImageIcon("./risorse/img/Tesserino.jpg"));
        }
        if (giocatore.getInventario().contieneItem(Items.CACCIAVITE)) {
            this.labelCacciavite.setIcon(new ImageIcon("./risorse/img/Cacciavite.jpg"));
        }
        if (giocatore.getInventario().contieneItem(Items.TELECOMANDO)) {
            this.labelTelecomando.setIcon(new ImageIcon("./risorse/img/Telecomando.jpg"));
        }
        if (giocatore.getInventario().contieneItem(Items.CHIAVE)) {
            this.labelChiave.setIcon(new ImageIcon("./risorse/img/Chiave.jpg"));
        }
        if (giocatore.getInventario().contieneItem(Items.FOGLIO)) {
            this.labelFoglio.setIcon(new ImageIcon("./risorse/img/Foglio.jpg"));
        }
        if (giocatore.getInventario().contieneItem(Items.TORCIA)) {
            this.labelTorcia.setIcon(new ImageIcon("./risorse/img/Torcia.jpg"));
        }
    }

    private void centraFrame() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTesserino = new javax.swing.JLabel();
        labelCacciavite = new javax.swing.JLabel();
        labelTelecomando = new javax.swing.JLabel();
        labelFoglio = new javax.swing.JLabel();
        labelChiave = new javax.swing.JLabel();
        labelTorcia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelTesserino.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTesserino, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCacciavite, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTelecomando, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelFoglio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelChiave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTorcia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelTorcia, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(labelChiave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFoglio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelecomando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTesserino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCacciavite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCacciavite;
    private javax.swing.JLabel labelChiave;
    private javax.swing.JLabel labelFoglio;
    private javax.swing.JLabel labelTelecomando;
    private javax.swing.JLabel labelTesserino;
    private javax.swing.JLabel labelTorcia;
    // End of variables declaration//GEN-END:variables
}
