/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaccia;

import controller.GestioneSalvataggi;
import entita.Giocatore;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author giuse
 */
public class InterfacciaAvvioGioco extends javax.swing.JFrame {

    private final Giocatore giocatore = new Giocatore("Utente");
    
    public InterfacciaAvvioGioco() {
        initComponents();
        inizializzaIcone();
        centraFrame();
    }
    
    private void centraFrame() {
        // Ottenere la dimensione dello schermo
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Ottenere la dimensione del frame
        Dimension frameSize = getSize();

        // Calcolare la posizione del frame per centrarlo
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;

        // Impostare la posizione del frame
        setLocation(x, y);
    }
    
    private void inizializzaIcone() {
        this.labelCopertina.setIcon(new ImageIcon("./risorse/img/Copertina.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCopertina = new javax.swing.JLabel();
        buttonNuovaPartita = new javax.swing.JButton();
        buttonContinua = new javax.swing.JButton();
        buttonEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AtomicQuest");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        buttonNuovaPartita.setBackground(new java.awt.Color(0, 102, 0));
        buttonNuovaPartita.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        buttonNuovaPartita.setForeground(new java.awt.Color(0, 0, 0));
        buttonNuovaPartita.setText("NUOVA PARTITA");
        buttonNuovaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuovaPartitaActionPerformed(evt);
            }
        });

        buttonContinua.setBackground(new java.awt.Color(0, 102, 0));
        buttonContinua.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        buttonContinua.setForeground(new java.awt.Color(0, 0, 0));
        buttonContinua.setText("CONTINUA");
        buttonContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinuaActionPerformed(evt);
            }
        });

        buttonEsci.setBackground(new java.awt.Color(0, 102, 0));
        buttonEsci.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        buttonEsci.setForeground(new java.awt.Color(0, 0, 0));
        buttonEsci.setText("ESCI");
        buttonEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(buttonNuovaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(buttonContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(buttonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(labelCopertina, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelCopertina, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonNuovaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuovaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuovaPartitaActionPerformed
        new InterfacciaGioco(this.giocatore).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonNuovaPartitaActionPerformed

    private void buttonEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsciActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonEsciActionPerformed

    private void buttonContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinuaActionPerformed
        if (GestioneSalvataggi.isDBVuoto())
            JOptionPane.showMessageDialog(this, "Non hai salvato nessuna partita");
        else {
            new InterfacciaGioco().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonContinuaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContinua;
    private javax.swing.JButton buttonEsci;
    private javax.swing.JButton buttonNuovaPartita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCopertina;
    // End of variables declaration//GEN-END:variables
}
