/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaccia;

import controller.AzioneSuInterfaccia;
import controller.GestioneSalvataggi;
import controller.OutputParser;
import controller.Parser;
import controller.RESTMeteoThread;
import entita.Giocatore;
import entita.LivelloRadioattivita;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author giuse
 */
public class InterfacciaGioco extends javax.swing.JFrame {

    private Parser parser;
    private OutputParser outputParser = new OutputParser();
    private AzioneSuInterfaccia azione;
    private Giocatore giocatore;
    
    public InterfacciaGioco(Giocatore giocatore) {
        initComponents();
        centraFrame();
        this.giocatore = giocatore;
        this.parser = new Parser(this.giocatore);
        this.inizializzaImmaginiLabel();
        new RESTMeteoThread(this.labelMeteo).visualizzaMeteo();
        String s = parser.getIntroduzione().getStringaDaStampare() + "\n Che vuoi fare? >> ";;
        new StampaThread(s, this.textAreaOutput, this.textFieldInput).stampa();
    }
    
    public InterfacciaGioco() {
        initComponents();
        centraFrame();
        Giocatore giocatore = GestioneSalvataggi.selezionaDaDB("Utente");
        this.giocatore = giocatore;
        this.parser = new Parser(this.giocatore);
        this.inizializzaImmaginiLabelDopoCaricamento();
        new RESTMeteoThread(this.labelMeteo).visualizzaMeteo();
        this.textAreaOutput.append(this.giocatore.getStanzaCorrente().getBenvenuto() + "\n Che vuoi fare? >> ");
    }
                
    
    
    private void inizializzaImmaginiLabel() {
        this.labelTuta.setIcon(new ImageIcon("./risorse/img/TutaIntegra.jpg"));
        this.labelTitolo.setIcon(new ImageIcon("./risorse/img/Titolo.png"));
        this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneBassa.jpg")); 
    }
    
    private void inizializzaImmaginiLabelDopoCaricamento() {
        this.labelTitolo.setIcon(new ImageIcon("./risorse/img/Titolo.png"));
        if (this.giocatore.isTutaIntegra())
            this.labelTuta.setIcon(new ImageIcon("./risorse/img/TutaIntegra.jpg"));
        else
            this.labelTuta.setIcon(new ImageIcon("./risorse/img/TutaRotta.jpg"));
        
        if (this.giocatore.getStanzaCorrente().getEsposizRadioattiva() == LivelloRadioattivita.BASSO)
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneBassa.jpg"));
        else if (this.giocatore.getStanzaCorrente().getEsposizRadioattiva() == LivelloRadioattivita.MEDIO)
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneMedia.jpg"));
        else if (this.giocatore.getStanzaCorrente().getEsposizRadioattiva() == LivelloRadioattivita.ELEVATO)
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneElevata.jpg"));
            
    }
    
    private void centraFrame() {
        // Ottenere la dimensione dello schermo
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Ottenere la dimensione del frame
        Dimension frameSize = getSize();

        // Calcolare la posizione del frame per centrarlo
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;

        // Impostare la posizione del frame
        setLocation(x, y);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipale = new javax.swing.JPanel();
        panelSinistra = new javax.swing.JPanel();
        barraScrolloTextArea = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        textFieldInput = new javax.swing.JTextField();
        labelTitolo = new javax.swing.JLabel();
        labelMeteo = new javax.swing.JLabel();
        buttonPausa = new javax.swing.JButton();
        buttonGuida = new javax.swing.JButton();
        panelDestra = new javax.swing.JPanel();
        labelTuta = new javax.swing.JLabel();
        buttonInventario = new javax.swing.JButton();
        labelRadioattivita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AtomicQuest");
        setResizable(false);

        panelPrincipale.setBackground(new java.awt.Color(0, 0, 0));

        panelSinistra.setBackground(new java.awt.Color(0, 0, 0));
        panelSinistra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        panelSinistra.setForeground(new java.awt.Color(255, 255, 255));

        barraScrolloTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 52, 0), 2));
        barraScrolloTextArea.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        barraScrolloTextArea.setAutoscrolls(true);

        textAreaOutput.setEditable(false);
        textAreaOutput.setBackground(new java.awt.Color(0, 0, 0));
        textAreaOutput.setColumns(20);
        textAreaOutput.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        textAreaOutput.setForeground(new java.awt.Color(0, 102, 0));
        textAreaOutput.setLineWrap(true);
        textAreaOutput.setRows(5);
        textAreaOutput.setWrapStyleWord(true);
        textAreaOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 52, 0), 2));
        barraScrolloTextArea.setViewportView(textAreaOutput);

        textFieldInput.setBackground(new java.awt.Color(51, 51, 0));
        textFieldInput.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        textFieldInput.setForeground(new java.awt.Color(0, 102, 0));
        textFieldInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        textFieldInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldInputActionPerformed(evt);
            }
        });

        buttonPausa.setText("PAUSA");
        buttonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPausaActionPerformed(evt);
            }
        });

        buttonGuida.setText("GUIDA");
        buttonGuida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSinistraLayout = new javax.swing.GroupLayout(panelSinistra);
        panelSinistra.setLayout(panelSinistraLayout);
        panelSinistraLayout.setHorizontalGroup(
            panelSinistraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinistraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSinistraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSinistraLayout.createSequentialGroup()
                        .addComponent(buttonPausa)
                        .addGap(18, 18, 18)
                        .addComponent(buttonGuida)
                        .addGap(5, 5, 5)
                        .addComponent(labelTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMeteo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(barraScrolloTextArea)
                    .addComponent(textFieldInput))
                .addContainerGap())
        );
        panelSinistraLayout.setVerticalGroup(
            panelSinistraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinistraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelSinistraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(buttonPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGuida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMeteo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraScrolloTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        panelDestra.setBackground(new java.awt.Color(0, 0, 0));
        panelDestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        buttonInventario.setBackground(new java.awt.Color(0, 102, 0));
        buttonInventario.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        buttonInventario.setForeground(new java.awt.Color(0, 0, 0));
        buttonInventario.setText("INVENTARIO");
        buttonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDestraLayout = new javax.swing.GroupLayout(panelDestra);
        panelDestra.setLayout(panelDestraLayout);
        panelDestraLayout.setHorizontalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDestraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRadioattivita, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(panelDestraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(labelTuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDestraLayout.setVerticalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRadioattivita, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelPrincipaleLayout = new javax.swing.GroupLayout(panelPrincipale);
        panelPrincipale.setLayout(panelPrincipaleLayout);
        panelPrincipaleLayout.setHorizontalGroup(
            panelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSinistra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPrincipaleLayout.setVerticalGroup(
            panelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipaleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSinistra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(panelPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldInputActionPerformed
        String s = this.textFieldInput.getText();
        this.textFieldInput.setText("");
        
        if (s.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Devi inserire un comando!");
        }
        else {
            
                this.outputParser = this.parser.analizzaComando(s);
                
                if (this.outputParser.getAzione().ordinal() == AzioneSuInterfaccia.FINE.ordinal()) {
                    new StampaThread("\n\n" + outputParser.getStringaDaStampare(), this.textAreaOutput, this.textFieldInput).stampa();
                    //this.textAreaOutput.append("\n\n" + outputParser.getStringaDaStampare());
                    this.gestisciFinale();
                    return;
                }
               
                this.textAreaOutput.append(s.toUpperCase() + "\n");
                new StampaThread("\n\n" + outputParser.getStringaDaStampare() +"\n Che vuoi fare? >> ", this.textAreaOutput, this.textFieldInput).stampa();
                //this.textAreaOutput.append(s.toUpperCase() + "\n\n" + outputParser.getStringaDaStampare() + "\n Che vuoi fare? ");
                if (this.outputParser.getAzione() == AzioneSuInterfaccia.TUTAINTEGRA || 
                    this.outputParser.getAzione() == AzioneSuInterfaccia.TUTAROTTA) {
                            this.gestisciLabelTuta();
                    }       
                if (this.outputParser.getAzione() == AzioneSuInterfaccia.RADIAZIONIBASSE || 
                    this.outputParser.getAzione() == AzioneSuInterfaccia.RADIAZIONIMEDIE || 
                    this.outputParser.getAzione() == AzioneSuInterfaccia.RADIAZIONIELEVATE) 
                {
                    this.gestisciLabelRadioattivita();
                }
        }
    }//GEN-LAST:event_textFieldInputActionPerformed

    private void buttonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInventarioActionPerformed
        new InterfacciaInventario(this.giocatore).setVisible(true);
    }//GEN-LAST:event_buttonInventarioActionPerformed

    private void buttonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPausaActionPerformed
        new InterfacciaPausa(this, this.giocatore).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonPausaActionPerformed

    private void buttonGuidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuidaActionPerformed
        new InterfacciaGuida().setVisible(true);
    }//GEN-LAST:event_buttonGuidaActionPerformed

    private void gestisciLabelTuta() {
        if (this.outputParser.getAzione() == AzioneSuInterfaccia.TUTAINTEGRA)
            this.labelTuta.setIcon(new ImageIcon("./risorse/img/TutaIntegra.jpg"));
        else
            this.labelTuta.setIcon(new ImageIcon("./risorse/img/TutaRotta.jpg"));
    }
    
    private void gestisciLabelRadioattivita() {
        
        if (this.outputParser.getAzione() == AzioneSuInterfaccia.RADIAZIONIBASSE)
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneBassa.jpg"));
        else if (this.outputParser.getAzione() == AzioneSuInterfaccia.RADIAZIONIMEDIE)
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneMedia.jpg"));
        else
            this.labelRadioattivita.setIcon(new ImageIcon("./risorse/img/RadiazioneElevata.jpg"));
    }
    
    private void gestisciFinale() {
        this.textFieldInput.setEditable(false);
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraScrolloTextArea;
    private javax.swing.JButton buttonGuida;
    private javax.swing.JButton buttonInventario;
    private javax.swing.JButton buttonPausa;
    private javax.swing.JLabel labelMeteo;
    private javax.swing.JLabel labelRadioattivita;
    private javax.swing.JLabel labelTitolo;
    private javax.swing.JLabel labelTuta;
    private javax.swing.JPanel panelDestra;
    private javax.swing.JPanel panelPrincipale;
    private javax.swing.JPanel panelSinistra;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextField textFieldInput;
    // End of variables declaration//GEN-END:variables
}
