
package entita;

public enum Stanze {
    CORTILE,
    ATRIO,
    SPOGLIATOIO,
    ANTICAMERASALAPOMPE,
    SALAPOMPE,
    ANTICAMERASALAVAPORE,
    SALAVAPORE,
    ANTICAMERASALAMACCHINE,
    SALAMACCHINE,
    CORRIDOIO,
    ANTICAMERASALAREATTORE,
    SALAREATTORE,
    SALACONTROLLO,
    ANTICAMERADEPOSITO,
    DEPOSITO,
    
}
