
package entita;

import java.io.Serializable;

public enum Stanze implements Serializable {
    CORTILE,
    ATRIO,
    SPOGLIATOIO,
    ANTICAMERASALAPOMPE,
    SALAPOMPE,
    ANTICAMERASALAVAPORE,
    SALAVAPORE,
    ANTICAMERASALAMACCHINE,
    SALAMACCHINE,
    CORRIDOIO,
    ANTICAMERASALAREATTORE,
    SALAREATTORE,
    SALACONTROLLO,
    ANTICAMERADEPOSITO,
    DEPOSITO,
    
}
