
package controller;


public enum AzioneSuInterfaccia {
    AGGIUNTACHIAVE,
    AGGIUNTATELECOMANDO,
    AGGIUNTACACCIAVITE,
    AGGIUNTATESSERINO,
    AGGIUNTAFOGLIO,
    AGGIUNTATORCIA,
    TUTAINTEGRA,
    TUTAROTTA,
    RADIAZIONIBASSE,
    RADIAZIONIMEDIE,
    RADIAZIONIELEVATE,
    METEOSOLE,
    METEOPIOGGIA,
    METEONUVOLE,
    FINE,
    NESSUNA
}
