
package controller;


public enum AzioneSuInterfaccia {
    AGGIUNTACHIAVE,
    RIMOZIONECHIAVE,
    AGGIUNTATELECOMANDO,
    RIMOZIONETELECOMANDO,
    AGGIUNTACACCIAVITE,
    RIMOZIONECACCIAVITE,
    AGGIUNTATESSERINO,
    RIMOZIONETESSERINO,
    AGGIUNTAFOGLIO,
    RIMOZIONEFOGLIO,
    AGGIUNTATORCIA,
    RIMOZIONETORCIA,
    TUTAINTEGRA,
    TUTAROTTA,
    RADIAZIONIBASSE,
    RADIAZIONIMEDIE,
    RADIAZIONIELEVATE,
    NESSUNA
}
